config/routes.rb
Rails.application.routes.draw do

  get '/auth/:provider/callback', to:'sessions#create'

  resources :users do
    resources :tasks do
      member do 
        post :set_time_tracking
        post :stop_tracking
      end
    end
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_many :tasks
  
  def self.find_or_create_from_auth_hash(auth_hash)
    user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
    user.update(
      name: auth_hash.info.nickname,
      profile_image: auth_hash.info.image,
      token: auth_hash.credentials.token,
      secret: auth_hash.credentials.secret
    )
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    redirect_to user_tasks_path(@user.id)
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def new
    @user = User.find(params[:user_id])
    @task = @user.tasks.build
	end

	def create
  		@task = Task.new(task_params)
      @task.user_id = current_user.id
      if @task.save
  		  redirect_to user_task_path(current_user, @task), :notice => "  task created!"
      else
        redirect_to new_user_task_path ,:alert => " sorry try again :("
      end    
	end
  
  def show
    @task = Task.find(params[:id])
  end
  
  def index
    @user =  User.find(params[:user_id])
    @tasks = @user.tasks.all
  end

  def set_time_tracking
    @task = Task.find(params[:id])
    @task.update_attributes(duration:params[:duration])
    respond_to do |format|
      format.json {render json: @task.duration}
    end
  end
 
private
  def task_params
    params.require(:task).permit(:user_id, :name, :duration, :text)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeawareTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <div class="navbar navbar-static-top navbar-inverse">
      <div class="navbar-inner">
        <a class="brand" href="#"></a>
        <%= link_to "TrackTest", root_path, :class=>"brand"%>
        <ul class="nav pull-right">
          <% if current_user %>
            <li><%= link_to current_user.name, user_tasks_path(current_user) %></li>
          <% else %>
            <li><a href="http://localhost:3000/auth/twitter"> login through twitter</a></li>
          <% end %> 
        </ul>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My tasks</h1>
  <% if @tasks.count<1 %>
    <p> You haven't registered any task. ¿Do you want to  <%= link_to 'create a new task', new_user_task_path%> now?</p>
  <% else %>
    <table class="table table-hover">
      <tr>
        <th>name</th>
        <th>duration</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
 
      <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task.name, user_task_path(@user, task)%></td>
          <td><%= task.duration %></td>
          <td><%= link_to 'Show', user_task_path(@user, task)%></td>
          <td><%= link_to 'Edit', edit_user_task_path(@user, task)%></td>
          <!-- <td>
            <%= link_to edit_user_task_path(@user, task) do %>
              <i class="icon-search"></i>
            <% end %>
          </td> -->
          <td><%= link_to 'Delete', user_task_path(@user, task), :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
      <% end %>
    </table>
    <br />
    <%= link_to 'create a new task', new_user_task_path, :class => "btn btn-primary" %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h2>new Task registration</h2>

  <%= form_for ([@user,@task]) do |f| %>
    <div><%= f.label :name %><br />
    <%= f.text_field :name %></div>

    <div><%= f.label :text %><br />
    <%= f.text_field :text %></div>

    <div><%= f.label :duration %><br />
    <%= f.text_field :duration %></div>


    <div><%= f.submit "create task",:class => "btn btn-primary" %></div>
  <% end %>
  <br />
  <%= link_to "Back", user_tasks_path,:class => "btn btn-primary"  %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="hero-unit">
    <h1>Task <%= @task.name %></h1>


    <table class="table table-condensed">
      <tr>
        <td><strong>Text</strong></td>
        <td><%= @task.text %></td>
      </tr>
      <tr>
        <td><strong>Created at</strong></td>
        <td><%= @task.created_at %></td>
      </tr>
      <tr>
        <td><strong>Duration</strong></td>
        <td>
          <p name='timer' class='form-control timer'>0 sec</p>
        </td>
      </tr>
    </table>
    <input type="hidden" class="task" task-id="<%= @task.id %>" user-id="<%= @task.user_id %>">
    <button class="btn btn-success start-timer-btn" type="button">Start Task</button>
    <button class='btn btn-success resume-timer-btn hide'>Resume</button>
    <button class='btn pause-timer-btn hide'>Pause</button>
    <button class='btn btn-danger remove-timer-btn hide'>Close Task</button>
  </div>
</div>  

app/views/welcome/index.html.erb
<div class="container">
  <h1>Welcome to your tracking App</h1>
  <div class="hero-unit">
    <% if current_user %>
      <h3>MyTracking</h3>
      </br>
      <%= image_tag(current_user.profile_image, class: "img-polaroid")%>
      <p> Hi <%=current_user.name%>! you are signed in, now you can see your <%= link_to "tasks list", user_tasks_path(current_user) %></p>
    <% else %>
      <div class="container-fluid">
        <div class="row-fluid">
          <div class="span2">
            <a href="http://localhost:3000/auth/twitter">
              <img src="/images/twitter-button.png"  alt="login through twitter" class="img-polaroid" width="140">
            </a>
          </div>
          <div class="span10">
            <p>Please press the twitter image to login, you will able to:</p>
            <ul>
              <li>View my tasks list.</li>
              <li>Create new Task</li>
              <li>Manage taks</li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>